### ISSUE TITLE
Use dotenv instead of env vars in webpack config

### ISSUE THREAD

**Issue by lucasbento** [learnrelay/learnrelay#48]
Use dotenv and provide only a `.env.example` file instead of setting everything on each webpack config file.

Something like https://github.com/lucasbento/react-relay-pokemon/blob/master/webpack.prod.config.js#L29 which is using [dotenv-webpack](https://github.com/mrsteele/dotenv-webpack).

**Comment by schickling** [comment]
Hey Lucas! Thanks for this suggestion. Is this based on you having a problem getting `learnrelay` up and running locally or rather in order to have a "better" tooling setup?

**Comment by lucasbento** [comment]
Hey @schickling, thanks for your quick response.

It's actually to have a better tooling setup, environment variables should _probably_ not be available for users since GitHub Client ID, Segment Token, etc only belong to this project and/or graphqlcool's, and _presumably_ should not be used by others.

**Comment by schickling** [comment]
I totally see your point! That's why we've created a dev stage for both `__GITHUB_OAUTH_CLIENT_ID__` and `__LAMBDA_AUTH__` which is preconfigured for convenience when running `npm start`.

I guess it's a good thing to keep the number of dependencies and additional tools to a minimum. If it add a lot of value in terms of DX I'd be happy though to merge it in.

**Comment by lucasbento** [comment]
Humm, I see.

Keeping the number of dependencies to a minimum definitely makes sense, I think we can close this issue then. :)

**Comment by schickling** [comment]
Thanks a lot for your insights and involvement though @lucasbento! 😊
